version: '3.7'
services:

  db:
    container_name: tbapp_db
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'tbapp'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      POSTGRES_ROOT_PASSWORD: '123'
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
       - postgres:/data/postgres
    networks:
      - postgres
      - nginx.docker
  pgadmin:
    container_name: pgadmin_tbapp_db
    image: dpage/pgadmin4:4.18
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin/
    ports:
      - "${PGADMIN_PORT:-5000}:80"
    networks:
      - postgres
    restart: unless-stopped
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:5001 app:app
    expose: 
      - 5001
    volumes:
      - ./back:/usr/src/back/
    env_file:
      - back/.env
    depends_on:
      - db
    networks:
      - postgres
      - nginx.docker
    restart: unless-stopped
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    depends_on:
      - back 
      - db
    volumes: 
      - ./front/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose: 
      - 80 
    env_file:
      - front/.env
    networks:
      - postgres
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true
  postgres:
    driver: bridge

volumes:
    pgadmin:
    postgres: