version: '3.7'

services:

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   expose: 
  #     - 3333
  #   volumes:
  #     - ./backend:/src/
  #   env_file:
  #     - backend/.env
  #   networks:
  #     - nginx.docker
  #   command: yarn start
  #   restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # depends_on:
    #   - backend
    volumes: 
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose: 
      - 80 
    networks:
      - nginx.docker

networks:
  nginx.docker:
    name: nginx.docker
    external: true